name: Sublimation
main: me.exphc.Sublimation.Sublimation
version: 1.0
permissions:
    sublimation.*:
        children: 
            sublimation.bypass: true
        default: false
    sublimation.bypass:
        description: Allows you to place ice in The Nether
        default: false
