name: Sublimation
main: me.exphc.Sublimation.Sublimation
version: 1.1
permissions:
    sublimation.*:
        children: 
            sublimation.bypass: true
            sublimation.collect: true
        default: false
    sublimation.bypass:
        description: Allows you to place ice in The Nether
        default: false
    sublimation.collect:
        description: Allows you to acquire ice mined with silk touch
        default: true
